Changed a reference to ConcurrentHashMap .ketSet() to keys() because the iterator returned by the first one has changed between Java 7 and Java 8, which can cause a java.lang.NoSuchMethodError runtime error.